### PR TITLE
Improve GNG formula by aligning to brew style

### PR DESCRIPTION
**Pull request by Mazorius**
I ran `brew style --fix gng` for the formula and also removed bottle as it is no longer supported by the latest Brew installation.

### CODE REVIEW

**Comment by Moulick** [comment]
@dantesun would be much appreciated if this can be merged, I love gng but this creates a lot of noise on every brew command run :(

**Comment by Mazorius** [comment]
Would fix #2

**Comment by csarmiento** [comment]
> @dantesun would be much appreciated if this can be merged, I love gng but this creates a lot of noise on every brew command run :(

@Moulick as a dirty hack you can apply the changes proposed in this PR directly to your local file: `/usr/local/Homebrew/Library/Taps/gdubw/homebrew-gng/Formula/gng.rb`

**Review by dantesun — APPROVED** [review]
Thank you for your contribution!

**Comment by Moulick** [comment]
> > @dantesun would be much appreciated if this can be merged, I love gng but this creates a lot of noise on every brew command run :(
> 
> @Moulick as a dirty hack you can apply the changes proposed in this PR directly to your local file: `/usr/local/Homebrew/Library/Taps/gdubw/homebrew-gng/Formula/gng.rb`

yeah, but that's the thing, didn't want to maintain this difference locally, otherwise I was thinking of making my own fork, but now it's merged so all good 🎉

**Pull request merged**
